// Builds the chatbot's knowledge base from the site's own published content.
//
// The corpus is small enough to live entirely in the model's system prompt, so
// there is no retrieval step: this script flattens each page to readable text
// and emits one module the Worker imports. Keeping the source of truth as the
// published pages is deliberate — the assistant cannot claim anything a visitor
// could not also read on the site, and editing a page updates the assistant.

import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outputPath = join(root, 'src/generated/corpus.js')

// Ordered most- to least-general, which is also the order the model reads them.
const SOURCES = [
  { file: 'docs/content/homepage.html', path: '/', title: 'Homepage' },
  { file: 'docs/content/about.html', path: '/about', title: 'About' },
  { file: 'docs/content/work/athena/index.html', path: '/work/athena', title: 'Athena — product story' },
  { file: 'docs/content/work/athena/local-first-pos/index.html', path: '/work/athena/local-first-pos', title: 'Athena — local-first point of sale' },
  { file: 'docs/content/work/athena/agent-ready-repository/index.html', path: '/work/athena/agent-ready-repository', title: 'Athena — agent-ready repository' },
  { file: 'docs/content/work/athena/read-optimized-reporting/index.html', path: '/work/athena/read-optimized-reporting', title: 'Athena — read-optimized reporting' },
  { file: 'docs/content/work/athena/evidence.md', path: null, title: 'Athena — evidence notes (not published as a page)' },
]

// Past this the system prompt stops being obviously cheap to send on every
// request and retrieval starts to earn its complexity. A warning rather than a
// failure: the build should not break because a page grew.
const TOKEN_BUDGET = 40_000

const ENTITIES = {
  amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ',
  mdash: '—', ndash: '–', hellip: '…', rsquo: '’', lsquo: '‘',
  rdquo: '”', ldquo: '“', times: '×', middot: '·',
}

function decodeEntities(text) {
  return text
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)))
    .replace(/&#x([0-9a-f]+);/gi, (_, code) => String.fromCodePoint(parseInt(code, 16)))
    .replace(/&([a-z]+);/gi, (match, name) => ENTITIES[name] ?? match)
}

// Alt text carries real content on the Athena pages — the workspace captures
// are described there and nowhere else — so images become a caption line
// rather than being dropped with the rest of the markup.
function htmlToText(html) {
  const body = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i)?.[1] ?? html

  const text = body
    .replace(/<(script|style|svg|noscript)\b[\s\S]*?<\/\1>/gi, ' ')
    .replace(/<img\b[^>]*\balt=["']([^"']+)["'][^>]*>/gi, '\n[image: $1]\n')
    .replace(/<h([1-6])\b[^>]*>/gi, (_, level) => `\n\n${'#'.repeat(Number(level))} `)
    .replace(/<\/h[1-6]>/gi, '\n')
    .replace(/<li\b[^>]*>/gi, '\n- ')
    .replace(/<(p|div|section|article|header|footer|tr|figcaption|blockquote)\b[^>]*>/gi, '\n')
    .replace(/<\/(p|div|section|article|header|footer|tr|figcaption|blockquote|ul|ol|li)>/gi, '\n')
    .replace(/<(td|th)\b[^>]*>/gi, ' | ')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<[^>]+>/g, '')

  return collapse(decodeEntities(text))
}

function collapse(text) {
  return text
    .split('\n')
    .map((line) => line.replace(/[ \t ]+/g, ' ').trim())
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

async function buildSection({ file, path, title }) {
  const raw = await readFile(join(root, file), 'utf8')
  const content = file.endsWith('.md') ? collapse(raw) : htmlToText(raw)
  // The page path lets the assistant point a reader at the page an answer came
  // from, which is the main thing that makes its answers checkable.
  const location = path ? `Page: ${path}` : 'Source: internal notes, no public page'

  return `<document title="${title}">\n${location}\n\n${content}\n</document>`
}

const sections = await Promise.all(SOURCES.map(buildSection))
const corpus = sections.join('\n\n')

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, `// Generated by scripts/build-corpus.mjs — do not edit.\nexport default ${JSON.stringify(corpus)}\n`)

// Roughly four characters per token; precise enough to catch a corpus that has
// outgrown the no-retrieval assumption.
const estimatedTokens = Math.round(corpus.length / 4)
console.log(`corpus: ${sections.length} documents, ${corpus.length} chars, ~${estimatedTokens} tokens`)
if (estimatedTokens > TOKEN_BUDGET) {
  console.warn(`corpus: ~${estimatedTokens} tokens exceeds the ${TOKEN_BUDGET} budget — consider retrieval instead of a whole-corpus system prompt`)
}
